/** Dublin neighbourhood names for host location selection. */
export const DUBLIN_AREAS = [
  "Ballsbridge",
  "City Centre",
  "Clontarf",
  "Docklands",
  "Drumcondra",
  "Dun Laoghaire",
  "Glasnevin",
  "Grand Canal Dock",
  "Howth",
  "Phibsborough",
  "Portobello",
  "Ranelagh",
  "Rathmines",
  "Sandymount",
  "Smithfield",
  "Stoneybatter",
  "Temple Bar",
  "Terenure",
  "The Liberties",
] as const;
